---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

driver_config:
    network:
    - ["forwarded_port", {guest: 80, host: 8999}]
    - ["forwarded_port", {guest: 5672, host: 5672}]
    - ["forwarded_port", {guest: 15672, host: 15672}]

suites:
  - name: default
    run_list: elk::default

    attributes:
